M48
; DRILL file {KiCad 7.0.6} date Sun May 26 17:55:56 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-05-26T17:55:56-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0827
%
G90
G05
T1
X4.8181Y-5.8905
X4.8339Y-1.7546
X6.7827Y-1.7546
X6.7945Y-5.8905
T0
M30
